envs:
  - HOST: "localhost"
  - PORT: "5432"
  - USERNAME: "lpusok"
  - PASSWORD: ""
  - DBNAME: "template1"
  - DBSSLMODE: "disable"
  - SCRIPTS_REPO: "git@github.com:lpusok/hackathon-data-scripts.git"